#---------------------------------------------------------
#  Task 1: Git/GitHub !
#
#
# Copyleft (c) by Vitali Lushchyk 2022
#
#--------------------------------------------------------

name: Task1
env: 
   Deploy_Ver             : ${{github.sha}}
   YEAR                   : 2022
   MONTH                  : February
   DAY_OF_THE_MONTH       : 15
   FAVORITE_DAY           : ${{secrets.FAVORITE_DAY_OF_WEEK}}



on:
  
  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  task1:
   
   
    runs-on   : ubuntu-latest
    
    defaults  :
       run    :
         working-directory: Task1
    
    steps:
      - name : Step 1 Fit clone my repo
        uses : actions/checkout@v1
      - name : Step 2 ls 
        run  : ls
      - name : Step 3 cat         
        run  : cat log.txt
      - name : Step 4 Deploy-Version          
        run  : echo "Deploy-Version = ${{env.Deploy_Ver}}"
        
          
  task2:
  
    runs-on: ubuntu-latest
    needs: [task1]
    
    
    steps: 
      - name : Step 1 Print the system date and time
        run   : date
      - name  : Step 2 Print DAY_OF_THE_MONTH
        run   : echo "DAY_OF_THE_MONTH = ${{env.DAY_OF_THE_MONTH}}"
      - name  : Step 3 Print MONTH
        run   : echo "MONTH = ${{env.MONTH}}"
      - name  : Step 4 Print YEAR
        run   : echo "YEAR = ${{env.YEAR}}"        
      - name  : Step 5 Print FAVORITE_DAY
        run   : echo "FAVORITE_DAY = ${{secrets.FAVORITE_DAY_OF_WEEK}}"
           
        
        

 
